---
apiVersion: v1
kind: Service
metadata:
  name: message-server
  labels:
    app: message-server
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: message-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server
spec:
  selector:
    matchLabels:
      app: message-server
  replicas: 2
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
      - name: message-server
        image: how2die/message-server
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
